version: '3.8'
services:
  explorer:
    image: kuzudb/explorer:latest
    ports:
      - "8080:8000"
    volumes:
      - ./api/demo_db/:/database
    restart: unless-stopped
  whodb:
    image: clidey/whodb
    volumes:  
       - ./api/db.sqlite:/db/db.sqlite
    ports:
      - "8080:8080"